# Generated by Django 4.2.6 on 2025-03-31 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0003_alter_piddata_options_remove_localdata_value7_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piddata',
            name='mass_flowmeter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piddata',
            name='no_of_bags',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
