# Generated by Django 4.2.6 on 2025-04-01 12:34

from django.db import migrations, models
import django.db.models.deletion
import irms_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0004_piddata_mass_flowmeter_piddata_no_of_bags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='irms_app.plant', verbose_name=irms_app.models.Plant),
            preserve_default=False,
        ),
    ]
