# Generated by Django 4.2.6 on 2025-04-02 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0005_customuser_plant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piddata',
            options={'verbose_name': 'Slurry and Purification Data', 'verbose_name_plural': 'Slurry and Purification Data'},
        ),
        migrations.CreateModel(
            name='PendingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.FloatField(blank=True, null=True)),
                ('value2', models.FloatField(blank=True, null=True)),
                ('value3', models.FloatField(blank=True, null=True)),
                ('value4', models.FloatField(blank=True, null=True)),
                ('value5', models.FloatField(blank=True, null=True)),
                ('value6', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irms_app.connection')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irms_app.plant')),
            ],
            options={
                'verbose_name': 'Pending Data',
                'verbose_name_plural': 'Pending Data',
                'db_table': 'pending_data',
            },
        ),
    ]
