# Generated by Django 4.2.6 on 2025-04-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0006_alter_piddata_options_pendingdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='plant_id',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='value5',
        ),
        migrations.RemoveField(
            model_name='pendingdata',
            name='value6',
        ),
        migrations.AddField(
            model_name='pendingdata',
            name='json_data',
            field=models.CharField(default=12, max_length=1000),
            preserve_default=False,
        ),
    ]
