# Generated by Django 5.2 on 2025-04-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0007_remove_pendingdata_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiogasPlantReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('feedstock_used_ton', models.FloatField()),
                ('feedstock_cost_per_ton', models.FloatField(blank=True, null=True)),
                ('total_feed_cost', models.FloatField()),
                ('raw_biogas_produced_nm3', models.FloatField()),
                ('methane_content_percent', models.FloatField()),
                ('expected_clean_gas_nm3', models.FloatField()),
                ('actual_clean_gas_nm3', models.FloatField()),
                ('purification_loss_nm3', models.FloatField()),
                ('purification_loss_percent', models.FloatField()),
                ('expected_production_kg', models.FloatField()),
                ('actual_cbg_production_kg', models.FloatField()),
                ('methane_loss_kg', models.FloatField()),
                ('methane_loss_percent', models.FloatField()),
                ('gas_purity_percent', models.FloatField()),
                ('power_consumption_kwh', models.FloatField()),
                ('power_cost_per_unit', models.FloatField(blank=True, null=True)),
                ('total_power_cost', models.FloatField()),
                ('co2_savings_mt', models.FloatField()),
                ('fom_bag_count', models.IntegerField(blank=True, null=True)),
                ('cbg_sale_dispatch_ton', models.FloatField(blank=True, null=True)),
                ('running_time', models.DurationField()),
                ('stoppage_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='CBGSaleDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dispatch Quantity (Ton)')),
                ('unit', models.CharField(default='Ton', max_length=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedstockCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Cost (Rs)')),
                ('cost_per_ton', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per Ton of Feed (Rs)')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PowerCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Power Cost (Rs)')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cost per Unit of Power (Rs)')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
