# Generated by Django 5.2 on 2025-04-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0008_biogasplantreport_cbgsaledispatch_feedstockcost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplantreport',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'General Shift'), ('Night Shift', 'Night Shift')], default='General Shift', max_length=20),
        ),
    ]
