# Generated by Django 4.2.7 on 2025-04-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0009_fomsaledispatch_remove_feedstockcost_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biogasplantreport',
            options={'verbose_name': 'Biogas Plant Report', 'verbose_name_plural': 'Biogas Plant Report'},
        ),
    ]
