# Generated by Django 4.2.7 on 2025-04-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0009_biogasplantreport_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOMSaleDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Dispatch Quantity (Ton)')),
                ('unit', models.CharField(default='Ton', max_length=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='biogasplantreport',
            options={'verbose_name': 'Biogas Plant Report', 'verbose_name_plural': 'Biogas Plant Report'},
        ),
        migrations.RemoveField(
            model_name='feedstockcost',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='powercost',
            name='cost',
        ),
    ]
