# Generated by Django 4.2.7 on 2025-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0010_fomsaledispatch_alter_biogasplantreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=20, null=True)),
                ('driver_status', models.CharField(max_length=2, null=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='connection',
            name='time_interval',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
