# Generated by Django 4.2.7 on 2025-05-12 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0011_driverstatus_connection_time_interval'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverstatus',
            options={'verbose_name': 'Driver Status', 'verbose_name_plural': 'Driver Status'},
        ),
        migrations.AlterModelTable(
            name='driverstatus',
            table='driverstatus',
        ),
    ]
