# Generated by Django 4.2.7 on 2025-05-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0012_alter_driverstatus_options_alter_driverstatus_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='time_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
