# Generated by Django 4.2.7 on 2025-05-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0014_rename_baloon_plc1_piddata_analyzer_ch4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biogasplantreport',
            name='report_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
