# Generated by Django 4.2.7 on 2025-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0015_biogasplantreport_report_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedHourlyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean_gas_production', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hourly Expected Clean Gas Production (Nm³)')),
                ('unit', models.CharField(default='Ton', max_length=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyExpectedCBGProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbg_production', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Hourly Expected CBG Production (kg)')),
                ('unit', models.CharField(default='Ton', max_length=10)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('set_point_1', models.FloatField()),
                ('set_point_2', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='biogasplantreport',
            options={'get_latest_by': 'id', 'verbose_name': 'Biogas Plant Report', 'verbose_name_plural': 'Biogas Plant Report'},
        ),
    ]
