# Generated by Django 4.2.7 on 2025-05-30 07:38

from django.db import migrations, models
import django.db.models.deletion
import irms_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0017_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biogasplantreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biogasplantreport',
            name='shift',
            field=models.CharField(choices=[('General Shift', 'General Shift'), ('Night Shift', 'Night Shift'), ('Evening Shift', 'Evening Shift')], default='General Shift', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='irms_app.plant', verbose_name=irms_app.models.Plant),
        ),
    ]
