# Generated by Django 4.2.7 on 2025-06-02 05:17

from django.db import migrations, models
import django.db.models.deletion
import irms_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('irms_app', '0018_alter_biogasplantreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='irms_app.plant', verbose_name=irms_app.models.Plant),
        ),
    ]
